### ISSUE TITLE
support outputs in bundle pkg

### ISSUE THREAD

**Issue by michelleN** [deislabs/cnab-go#14]
as per the `bundle.json` [description](https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md) and the [outputs PR](https://github.com/deislabs/cnab-spec/pull/133) on the cnab spec

**Comment by radu-matei** [comment]
The parameters part of the specification also needs to be updated for the JSON schema, and the main question here is how to approach adding JSON schema support in all places where it is required, and also be consistent and _not reimplement_ the schema itself and the validation.

@carolynvs might have some thoughts about this, since she implemented parts of this for Porter.

**Comment by jeremyrickard** [comment]
@radu-matei we added some json schema validation w/ the mixins but not at the bundle level yet (each of the mixins has it's own pre-known schema and we're using a library to validate that).

I think we can probably refactor part of that out and update cnab-go to have some common functions for dealing with bundle parameter definitions. I opened a separate issue to update to the rest of the parameter definition stuff as well (see: #17).
